export const VARIABLE_DEFINITIONS = {
	match_id: { name: 'Selected match id' },
	match_title: { name: 'Match title ("Player 1 vs Player 2")' },
	player1_name: { name: 'Player 1 name' },
	player2_name: { name: 'Player 2 name' },
	player1_country: { name: 'Player 1 country (IOC code)' },
	player2_country: { name: 'Player 2 country (IOC code)' },
	player1_ranking: { name: 'Player 1 official singles ranking' },
	player2_ranking: { name: 'Player 2 official singles ranking' },
	sets: { name: 'Sets won ("1-0")' },
	games: { name: 'Games per set ("6-4 3-4")' },
	points: { name: 'Points in the current game ("40-30"; tiebreak count during a tiebreak)' },
	score_line: { name: 'Games + points on one line ("6-4 3-4 40-30")' },
	current_set: { name: 'Number of the set in progress' },
	current_set_games: { name: 'Games in the set in progress ("3-4")' },
	set_scores: { name: 'All set scores separated by spaces' },
	set1: { name: 'Set 1 games' },
	set2: { name: 'Set 2 games' },
	set3: { name: 'Set 3 games' },
	set4: { name: 'Set 4 games' },
	set5: { name: 'Set 5 games' },
	server: { name: 'Serving player (1 or 2; empty when unknown or not live)' },
	server_name: { name: 'Serving player name' },
	break_point: { name: 'Break point in progress (true/false)' },
	break_point_player: { name: 'Player holding the break point (1 or 2)' },
	break_point_player_name: { name: 'Name of the player holding the break point' },
	tiebreak: { name: 'Tiebreak in progress (true/false)' },
	match_status: { name: 'Match status ("live", "completed", "live (Interrupted)", "no match")' },
	event_status: { name: 'Event status (Retired, Walk Over, Interrupted, ...)' },
	outcome: { name: 'Settlement outcome (completed, retired, walkover, ...)' },
	winner: { name: 'Winner (1 or 2) once completed' },
	winner_name: { name: 'Winner name once completed' },
	tournament: { name: 'Tournament name' },
	round: { name: 'Round' },
	round_code: { name: 'Round code (F, SF, QF, R16, ...)' },
	surface: { name: 'Surface' },
	tour: { name: 'Tour (atp, wta, challenger, itf)' },
	draw: { name: 'Draw (singles/doubles)' },
	format: { name: 'Format (BO3/BO5)' },
	score_timestamp: { name: 'API timestamp of the score' },
	last_updated: { name: 'Last successful poll (ISO 8601 UTC)' },
	last_updated_time: { name: 'Last successful poll, time only (HH:MM:SS UTC)' },
	api_error: { name: 'Current API problem (empty when healthy)' },
	live_count: { name: 'Number of live matches in the last list' },
	live_index: { name: 'Position of the selected match in the live list (1-based)' },
	poll_interval: { name: 'Effective poll interval in seconds' },
	requests_today: { name: 'Requests this module has made today (UTC)' },
}

export function updateVariableDefinitions(self) {
	self.setVariableDefinitions(VARIABLE_DEFINITIONS)
}
